version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - aws cloudformation package --template-file pdftotxt.yaml --s3-bucket my-search-artifacts-e3 --output-template-file lambda-pdf-to-text/lambdaoutput.yaml

artifacts:
  type: zip
  files:
    - pdftotxt.yaml
    - lambdaoutput.yaml