version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - aws cloudformation package --template-file lambda-pdf-to-text/pdftotxt.yaml --s3-bucket my-search-artifacts-e3 --output-template-file lambdaoutput.yaml

artifacts:
  files:
    - lambda-pdf-to-text/pdftotxt.yaml
    - lambdaoutput.yaml