AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: .
      Description: ''
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::998956253504:role/lambda-pdftotxt-exec-role'
      Environment:
        Variables:
          TARGET_BUCKET: my-search-intermediate-e3
      Layers:
        - 'arn:aws:lambda:us-east-2:998956253504:layer:pypdf-layer:2'
