version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - aws cloudformation package --template-file search-function/search-function.yaml --s3-bucket my-search-artifacts-e3 --output-template-file search.yaml

artifacts:
  type: zip
  files:
    - search-function.yaml
    - search.yaml
